// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AccessKeyInitParameters struct {

	// (Boolean) Whether the access key is enabled.
	// Whether the access key is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) A display name for the access key.
	// A display name for the access key.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the product environment this access key belongs to. Changing this value forces a new resource to be created.
	// The ID of the product environment this access key belongs to. Changing this value forces a new resource to be created.
	ProductEnvironmentID *string `json:"productEnvironmentId,omitempty" tf:"product_environment_id,omitempty"`
}

type AccessKeyObservation struct {

	// (String) The API key identifier.
	// The API key identifier.
	APIKey *string `json:"apiKey,omitempty" tf:"api_key,omitempty"`

	// (String) The time at which the access key was created (RFC3339).
	// The time at which the access key was created (RFC3339).
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// (Boolean) Whether the access key is enabled.
	// Whether the access key is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) A display name for the access key.
	// A display name for the access key.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the product environment this access key belongs to. Changing this value forces a new resource to be created.
	// The ID of the product environment this access key belongs to. Changing this value forces a new resource to be created.
	ProductEnvironmentID *string `json:"productEnvironmentId,omitempty" tf:"product_environment_id,omitempty"`

	// (String) The time at which the access key was last updated (RFC3339).
	// The time at which the access key was last updated (RFC3339).
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type AccessKeyParameters struct {

	// (Boolean) Whether the access key is enabled.
	// Whether the access key is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) A display name for the access key.
	// A display name for the access key.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The ID of the product environment this access key belongs to. Changing this value forces a new resource to be created.
	// The ID of the product environment this access key belongs to. Changing this value forces a new resource to be created.
	// +kubebuilder:validation:Optional
	ProductEnvironmentID *string `json:"productEnvironmentId,omitempty" tf:"product_environment_id,omitempty"`
}

// AccessKeySpec defines the desired state of AccessKey
type AccessKeySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AccessKeyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AccessKeyInitParameters `json:"initProvider,omitempty"`
}

// AccessKeyStatus defines the observed state of AccessKey.
type AccessKeyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AccessKeyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AccessKey is the Schema for the AccessKeys API. Manages an API access key for a Cloudinary product environment. Access keys provide the credentials needed to interact with a product environment's API.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudinaryprovisioning}
type AccessKey struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.productEnvironmentId) || (has(self.initProvider) && has(self.initProvider.productEnvironmentId))",message="spec.forProvider.productEnvironmentId is a required parameter"
	Spec   AccessKeySpec   `json:"spec"`
	Status AccessKeyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AccessKeyList contains a list of AccessKeys
type AccessKeyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AccessKey `json:"items"`
}

// Repository type metadata.
var (
	AccessKey_Kind             = "AccessKey"
	AccessKey_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AccessKey_Kind}.String()
	AccessKey_KindAPIVersion   = AccessKey_Kind + "." + CRDGroupVersion.String()
	AccessKey_GroupVersionKind = CRDGroupVersion.WithKind(AccessKey_Kind)
)

func init() {
	SchemeBuilder.Register(&AccessKey{}, &AccessKeyList{})
}
