// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type PrincipalRoleAssignmentInitParameters struct {

	// (String) The unique identifier of the principal.
	// The unique identifier of the principal.
	PrincipalID *string `json:"principalId,omitempty" tf:"principal_id,omitempty"`

	// (String) The type of principal. Must be one of: "user", "group", "apiKey", "provisioningKey".
	// The type of principal. Must be one of: "user", "group", "apiKey", "provisioningKey".
	PrincipalType *string `json:"principalType,omitempty" tf:"principal_type,omitempty"`

	// (String) The unique identifier of the role to assign.
	// The unique identifier of the role to assign.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// (String) The ID of the product environment. Required when scope_type is "prodenv". Must be omitted when scope_type is "account".
	// The ID of the product environment. Required when scope_type is "prodenv". Must be omitted when scope_type is "account".
	ScopeID *string `json:"scopeId,omitempty" tf:"scope_id,omitempty"`

	// (String) The scope level. Must be one of: "account" (whole account) or "prodenv" (specific product environment).
	// The scope level. Must be one of: "account" (whole account) or "prodenv" (specific product environment).
	ScopeType *string `json:"scopeType,omitempty" tf:"scope_type,omitempty"`
}

type PrincipalRoleAssignmentObservation struct {

	// (String) Composite identifier: {principal_type}/{principal_id}/{role_id}/{scope_type}/{scope_id}.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The unique identifier of the principal.
	// The unique identifier of the principal.
	PrincipalID *string `json:"principalId,omitempty" tf:"principal_id,omitempty"`

	// (String) The type of principal. Must be one of: "user", "group", "apiKey", "provisioningKey".
	// The type of principal. Must be one of: "user", "group", "apiKey", "provisioningKey".
	PrincipalType *string `json:"principalType,omitempty" tf:"principal_type,omitempty"`

	// (String) The unique identifier of the role to assign.
	// The unique identifier of the role to assign.
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// (String) The ID of the product environment. Required when scope_type is "prodenv". Must be omitted when scope_type is "account".
	// The ID of the product environment. Required when scope_type is "prodenv". Must be omitted when scope_type is "account".
	ScopeID *string `json:"scopeId,omitempty" tf:"scope_id,omitempty"`

	// (String) The scope level. Must be one of: "account" (whole account) or "prodenv" (specific product environment).
	// The scope level. Must be one of: "account" (whole account) or "prodenv" (specific product environment).
	ScopeType *string `json:"scopeType,omitempty" tf:"scope_type,omitempty"`
}

type PrincipalRoleAssignmentParameters struct {

	// (String) The unique identifier of the principal.
	// The unique identifier of the principal.
	// +kubebuilder:validation:Optional
	PrincipalID *string `json:"principalId,omitempty" tf:"principal_id,omitempty"`

	// (String) The type of principal. Must be one of: "user", "group", "apiKey", "provisioningKey".
	// The type of principal. Must be one of: "user", "group", "apiKey", "provisioningKey".
	// +kubebuilder:validation:Optional
	PrincipalType *string `json:"principalType,omitempty" tf:"principal_type,omitempty"`

	// (String) The unique identifier of the role to assign.
	// The unique identifier of the role to assign.
	// +kubebuilder:validation:Optional
	RoleID *string `json:"roleId,omitempty" tf:"role_id,omitempty"`

	// (String) The ID of the product environment. Required when scope_type is "prodenv". Must be omitted when scope_type is "account".
	// The ID of the product environment. Required when scope_type is "prodenv". Must be omitted when scope_type is "account".
	// +kubebuilder:validation:Optional
	ScopeID *string `json:"scopeId,omitempty" tf:"scope_id,omitempty"`

	// (String) The scope level. Must be one of: "account" (whole account) or "prodenv" (specific product environment).
	// The scope level. Must be one of: "account" (whole account) or "prodenv" (specific product environment).
	// +kubebuilder:validation:Optional
	ScopeType *string `json:"scopeType,omitempty" tf:"scope_type,omitempty"`
}

// PrincipalRoleAssignmentSpec defines the desired state of PrincipalRoleAssignment
type PrincipalRoleAssignmentSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     PrincipalRoleAssignmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider PrincipalRoleAssignmentInitParameters `json:"initProvider,omitempty"`
}

// PrincipalRoleAssignmentStatus defines the observed state of PrincipalRoleAssignment.
type PrincipalRoleAssignmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        PrincipalRoleAssignmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// PrincipalRoleAssignment is the Schema for the PrincipalRoleAssignments API. Assigns a role to a principal (user, group, API key, or provisioning key) within a given scope. All attributes are immutable: any change forces resource replacement.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudinaryprovisioning}
type PrincipalRoleAssignment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.principalId) || (has(self.initProvider) && has(self.initProvider.principalId))",message="spec.forProvider.principalId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.principalType) || (has(self.initProvider) && has(self.initProvider.principalType))",message="spec.forProvider.principalType is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.roleId) || (has(self.initProvider) && has(self.initProvider.roleId))",message="spec.forProvider.roleId is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scopeType) || (has(self.initProvider) && has(self.initProvider.scopeType))",message="spec.forProvider.scopeType is a required parameter"
	Spec   PrincipalRoleAssignmentSpec   `json:"spec"`
	Status PrincipalRoleAssignmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// PrincipalRoleAssignmentList contains a list of PrincipalRoleAssignments
type PrincipalRoleAssignmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []PrincipalRoleAssignment `json:"items"`
}

// Repository type metadata.
var (
	PrincipalRoleAssignment_Kind             = "PrincipalRoleAssignment"
	PrincipalRoleAssignment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: PrincipalRoleAssignment_Kind}.String()
	PrincipalRoleAssignment_KindAPIVersion   = PrincipalRoleAssignment_Kind + "." + CRDGroupVersion.String()
	PrincipalRoleAssignment_GroupVersionKind = CRDGroupVersion.WithKind(PrincipalRoleAssignment_Kind)
)

func init() {
	SchemeBuilder.Register(&PrincipalRoleAssignment{}, &PrincipalRoleAssignmentList{})
}
