apiVersion: iam.cloudinaryprovisioning.m.crossplane.io/v1alpha1
kind: PrincipalRoleAssignment
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1alpha1/principalroleassignment
  labels:
    testing.upbound.io/example-name: provisioning_key_admin
  name: provisioning-key-admin
  namespace: crossplane-system
spec:
  forProvider:
    principalId: ${data.cloudinaryprovisioning_current_principal.me.principal_id}
    principalType: ${data.cloudinaryprovisioning_current_principal.me.principal_type}
    roleId: ${data.cloudinaryprovisioning_role.admin.id}
    scopeId: ${cloudinaryprovisioning_product_environment.dev.id}
    scopeType: prodenv
