// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type CustomPolicyInitParameters struct {

	// readable description of the custom policy.
	// A human-readable description of the custom policy.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the custom policy is enabled.
	// Whether the custom policy is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The display name of the custom policy.
	// The display name of the custom policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The Cedar policy statement string.
	// The Cedar policy statement string.
	PolicyStatement *string `json:"policyStatement,omitempty" tf:"policy_statement,omitempty"`

	// (String) The ID of the product environment this policy applies to. Required when scope_type is "prodenv". Must be omitted or empty when scope_type is "account".
	// The ID of the product environment this policy applies to. Required when scope_type is "prodenv". Must be omitted or empty when scope_type is "account".
	ScopeID *string `json:"scopeId,omitempty" tf:"scope_id,omitempty"`

	// (String) The scope of the policy. Must be one of: "account" (applies to the whole account) or "prodenv" (applies to a specific product environment).
	// The scope of the policy. Must be one of: "account" (applies to the whole account) or "prodenv" (applies to a specific product environment).
	ScopeType *string `json:"scopeType,omitempty" tf:"scope_type,omitempty"`
}

type CustomPolicyObservation struct {

	// (String) The Unix timestamp at which the custom policy was created.
	// The Unix timestamp at which the custom policy was created.
	CreatedAt *string `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// readable description of the custom policy.
	// A human-readable description of the custom policy.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the custom policy is enabled.
	// Whether the custom policy is enabled.
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The unique identifier of the custom policy assigned by Cloudinary.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (String) The display name of the custom policy.
	// The display name of the custom policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The Cedar policy statement string.
	// The Cedar policy statement string.
	PolicyStatement *string `json:"policyStatement,omitempty" tf:"policy_statement,omitempty"`

	// (String) The ID of the product environment this policy applies to. Required when scope_type is "prodenv". Must be omitted or empty when scope_type is "account".
	// The ID of the product environment this policy applies to. Required when scope_type is "prodenv". Must be omitted or empty when scope_type is "account".
	ScopeID *string `json:"scopeId,omitempty" tf:"scope_id,omitempty"`

	// (String) The scope of the policy. Must be one of: "account" (applies to the whole account) or "prodenv" (applies to a specific product environment).
	// The scope of the policy. Must be one of: "account" (applies to the whole account) or "prodenv" (applies to a specific product environment).
	ScopeType *string `json:"scopeType,omitempty" tf:"scope_type,omitempty"`

	// (String) The Unix timestamp at which the custom policy was last updated.
	// The Unix timestamp at which the custom policy was last updated.
	UpdatedAt *string `json:"updatedAt,omitempty" tf:"updated_at,omitempty"`
}

type CustomPolicyParameters struct {

	// readable description of the custom policy.
	// A human-readable description of the custom policy.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Boolean) Whether the custom policy is enabled.
	// Whether the custom policy is enabled.
	// +kubebuilder:validation:Optional
	Enabled *bool `json:"enabled,omitempty" tf:"enabled,omitempty"`

	// (String) The display name of the custom policy.
	// The display name of the custom policy.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// (String) The Cedar policy statement string.
	// The Cedar policy statement string.
	// +kubebuilder:validation:Optional
	PolicyStatement *string `json:"policyStatement,omitempty" tf:"policy_statement,omitempty"`

	// (String) The ID of the product environment this policy applies to. Required when scope_type is "prodenv". Must be omitted or empty when scope_type is "account".
	// The ID of the product environment this policy applies to. Required when scope_type is "prodenv". Must be omitted or empty when scope_type is "account".
	// +kubebuilder:validation:Optional
	ScopeID *string `json:"scopeId,omitempty" tf:"scope_id,omitempty"`

	// (String) The scope of the policy. Must be one of: "account" (applies to the whole account) or "prodenv" (applies to a specific product environment).
	// The scope of the policy. Must be one of: "account" (applies to the whole account) or "prodenv" (applies to a specific product environment).
	// +kubebuilder:validation:Optional
	ScopeType *string `json:"scopeType,omitempty" tf:"scope_type,omitempty"`
}

// CustomPolicySpec defines the desired state of CustomPolicy
type CustomPolicySpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     CustomPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider CustomPolicyInitParameters `json:"initProvider,omitempty"`
}

// CustomPolicyStatus defines the observed state of CustomPolicy.
type CustomPolicyStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        CustomPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// CustomPolicy is the Schema for the CustomPolicys API. Manages a Cloudinary custom permissions policy. Custom policies allow fine-grained access control over Cloudinary resources using Cedar policy language.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,cloudinaryprovisioning}
type CustomPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.policyStatement) || (has(self.initProvider) && has(self.initProvider.policyStatement))",message="spec.forProvider.policyStatement is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.scopeType) || (has(self.initProvider) && has(self.initProvider.scopeType))",message="spec.forProvider.scopeType is a required parameter"
	Spec   CustomPolicySpec   `json:"spec"`
	Status CustomPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// CustomPolicyList contains a list of CustomPolicys
type CustomPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []CustomPolicy `json:"items"`
}

// Repository type metadata.
var (
	CustomPolicy_Kind             = "CustomPolicy"
	CustomPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: CustomPolicy_Kind}.String()
	CustomPolicy_KindAPIVersion   = CustomPolicy_Kind + "." + CRDGroupVersion.String()
	CustomPolicy_GroupVersionKind = CRDGroupVersion.WithKind(CustomPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&CustomPolicy{}, &CustomPolicyList{})
}
