//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPolicy) DeepCopyInto(out *CustomPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPolicy.
func (in *CustomPolicy) DeepCopy() *CustomPolicy {
	if in == nil {
		return nil
	}
	out := new(CustomPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPolicyInitParameters) DeepCopyInto(out *CustomPolicyInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PolicyStatement != nil {
		in, out := &in.PolicyStatement, &out.PolicyStatement
		*out = new(string)
		**out = **in
	}
	if in.ScopeID != nil {
		in, out := &in.ScopeID, &out.ScopeID
		*out = new(string)
		**out = **in
	}
	if in.ScopeType != nil {
		in, out := &in.ScopeType, &out.ScopeType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPolicyInitParameters.
func (in *CustomPolicyInitParameters) DeepCopy() *CustomPolicyInitParameters {
	if in == nil {
		return nil
	}
	out := new(CustomPolicyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPolicyList) DeepCopyInto(out *CustomPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]CustomPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPolicyList.
func (in *CustomPolicyList) DeepCopy() *CustomPolicyList {
	if in == nil {
		return nil
	}
	out := new(CustomPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *CustomPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPolicyObservation) DeepCopyInto(out *CustomPolicyObservation) {
	*out = *in
	if in.CreatedAt != nil {
		in, out := &in.CreatedAt, &out.CreatedAt
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PolicyStatement != nil {
		in, out := &in.PolicyStatement, &out.PolicyStatement
		*out = new(string)
		**out = **in
	}
	if in.ScopeID != nil {
		in, out := &in.ScopeID, &out.ScopeID
		*out = new(string)
		**out = **in
	}
	if in.ScopeType != nil {
		in, out := &in.ScopeType, &out.ScopeType
		*out = new(string)
		**out = **in
	}
	if in.UpdatedAt != nil {
		in, out := &in.UpdatedAt, &out.UpdatedAt
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPolicyObservation.
func (in *CustomPolicyObservation) DeepCopy() *CustomPolicyObservation {
	if in == nil {
		return nil
	}
	out := new(CustomPolicyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPolicyParameters) DeepCopyInto(out *CustomPolicyParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.Enabled != nil {
		in, out := &in.Enabled, &out.Enabled
		*out = new(bool)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.PolicyStatement != nil {
		in, out := &in.PolicyStatement, &out.PolicyStatement
		*out = new(string)
		**out = **in
	}
	if in.ScopeID != nil {
		in, out := &in.ScopeID, &out.ScopeID
		*out = new(string)
		**out = **in
	}
	if in.ScopeType != nil {
		in, out := &in.ScopeType, &out.ScopeType
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPolicyParameters.
func (in *CustomPolicyParameters) DeepCopy() *CustomPolicyParameters {
	if in == nil {
		return nil
	}
	out := new(CustomPolicyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPolicySpec) DeepCopyInto(out *CustomPolicySpec) {
	*out = *in
	in.ResourceSpec.DeepCopyInto(&out.ResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPolicySpec.
func (in *CustomPolicySpec) DeepCopy() *CustomPolicySpec {
	if in == nil {
		return nil
	}
	out := new(CustomPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomPolicyStatus) DeepCopyInto(out *CustomPolicyStatus) {
	*out = *in
	in.ResourceStatus.DeepCopyInto(&out.ResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomPolicyStatus.
func (in *CustomPolicyStatus) DeepCopy() *CustomPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(CustomPolicyStatus)
	in.DeepCopyInto(out)
	return out
}
